import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import assert from 'node:assert/strict';import vm from 'node:vm';import {randomUUID} from 'node:crypto';
const sqlite=new DatabaseSync(':memory:');for(const file of JSON.parse(fs.readFileSync('drizzle/meta/_journal.json','utf8')).entries.map(e=>e.tag+'.sql'))sqlite.exec(fs.readFileSync('drizzle/'+file,'utf8'));
const DB={prepare(sql){const stmt=sqlite.prepare(sql);return{bind(...args){return{async first(){return stmt.get(...args)||null},async all(){return{results:stmt.all(...args)}},async run(){return{meta:stmt.run(...args)}}}}}}};
const {default:worker}=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync('worker/index.js','utf8')).toString('base64'));
const env={DB,SETTINGS_ENCRYPTION_KEY:'01'.repeat(32)};
async function call(path,method='GET',data){return worker.fetch(new Request('https://example.com'+path,{method,headers:{Origin:'https://example.com'},...(data?{body:JSON.stringify(data)}:{})}),env,{})}
const config={aiEnabled:false,aiInstructions:'',aiRegistration:'',aiHandoff:'',offer:'Cardápio digital e 30 dias grátis',tone:'Natural',length:'Curta',emojis:true,templates:{initial:'Oi {empresa}',presentation:'Apresentação',promotion:'Promoção',followup:'Retorno',trial:'Teste'}};
assert((await (await call('/api/settings')).json()).config.templates.trial);
let response=await call('/api/settings','PUT',{config,apiKey:'test-only-key'});assert.equal(response.status,200);let settings=await response.json();assert.equal(settings.hasApiKey,true);assert(!JSON.stringify(settings).includes('test-only-key'));assert(!sqlite.prepare('SELECT key_cipher FROM settings').get().key_cipher.includes('test-only-key'));
await call('/api/settings','PUT',{config:{...config,offer:'Nova oferta'},initializeOnly:true});assert.equal((await (await call('/api/settings')).json()).config.offer,config.offer);
const originalFetch=globalThis.fetch;globalThis.fetch=async(url,options)=>{assert.equal(options.headers['x-goog-api-key'],'test-only-key');return Response.json({candidates:[{content:{parts:[{text:'Texto criado'}]}}]})};response=await call('/api/generate-message','POST',{company:'Empresa',niche:'Delivery',goal:'Apresentar um serviço',tone:'Natural',length:'Curta',emojis:true,details:config.offer,current:'Oi'});assert.equal((await response.json()).message,'Texto criado');globalThis.fetch=originalFetch;
const entry={id:randomUUID(),company:'Loja Teste',phone:'5513991424545',message:'Olá',type:'Mensagem inicial',date:new Date().toISOString()};await call('/api/history','POST',entry);await call('/api/history','POST',entry);let list=(await (await call('/api/history')).json()).entries;assert.equal(list.length,1);assert.equal(list[0].status,'opened');await call('/api/history/'+entry.id,'PATCH',{});assert.equal((await (await call('/api/history')).json()).entries[0].status,'sent');
const html=fs.readFileSync('worker/page.html','utf8');const fields={};const make=()=>({value:'',hidden:false,checked:false,children:[],classList:{toggle(){}},addEventListener(e,f){this[e]=f},focus(){},setAttribute(){},replaceChildren(){this.children=[]},append(...a){this.children.push(...a)},select(){},setSelectionRange(){}});for(const m of html.matchAll(/id="([^"]+)"/g))fields[m[1]]=make();fields.type.value='initial';fields.niche.value='Delivery';fields.output.hidden=true;
const context={structuredClone,crypto:{randomUUID},confirm:()=>true,document:{getElementById:id=>fields[id],createElement(){const el=make();Object.defineProperty(el,'id',{set(id){fields[id]=el}});return el}},localStorage:{getItem(){return null},removeItem(){}},navigator:{},fetch:(path,options={})=>call(path,options.method||'GET',options.body?JSON.parse(options.body):undefined)};
vm.createContext(context);vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);await vm.runInContext('initializeDatabase()',context);assert.equal(fields.offer.value,config.offer);assert(fields['key-saved-status'].textContent.includes('salva'));fields.offer.value='Oferta em outra máquina';await fields['save-settings'].click();assert.equal((await (await call('/api/settings')).json()).config.offer,'Oferta em outra máquina');await vm.runInContext('renderHistory()',context);assert.equal(fields['history-rows'].children.length,1);assert(fields['history-rows'].children[0].children[3].textContent.includes('Enviado'));
fields['api-key'].value='replacement-test-key';await fields['save-key'].click();assert.equal(fields['api-key'].value,'');assert(fields['key-saved-status'].textContent.includes('salva'));const unchanged=(await (await call('/api/settings')).json()).config;assert.equal(unchanged.offer,'Oferta em outra máquina');assert.equal(fields['save-key'].disabled,false);
await call('/api/settings','PUT',{config,removeApiKey:true});assert.equal((await (await call('/api/settings')).json()).hasApiKey,false);
console.log('Banco compartilhado, criptografia da chave, leitura sem exposição, histórico idempotente e interface verificados.');
// Queue sends through the provider and preserves the exact accepted message and contact identity.
response=await call('/api/contacts/import','POST',{city:'Pariquera-Açu',contacts:[{company:'Empresa Teste',phone:'13999999999'}]});assert.equal(response.status,200);
let contact=(await (await call('/api/contacts')).json()).contacts[0];
assert.equal((await call('/api/contacts/'+contact.id,'PATCH',{company:'Nome editado',phone:contact.phone,city:contact.city,responsible:'Fernando',notes:'Cadastro completo'})).status,200);
assert.equal((await (await call('/api/contacts')).json()).contacts[0].company,'Nome editado');
await call('/api/queue','POST',{contactIds:[contact.id]});
assert.equal((await call('/api/queue/control','POST',{action:'START'})).status,409);
await call('/api/queue/prepare','POST',{type:'initial',mode:'STANDARD'});
const prepared=(await (await call('/api/queue')).json()).entries[0];assert.equal(JSON.parse(prepared.message).text,'Oi Nome editado');
await call('/api/instances','POST',{name:'Teste',apiUrl:'https://provider.test',token:'mock-token',minSeconds:10,maxSeconds:10,messagesPerCycle:10});
sqlite.exec("UPDATE instances SET status='CONNECTED'");
assert.equal((await call('/api/queue/control','POST',{action:'START'})).status,200);
let sends=0;globalThis.fetch=async(url,options)=>{sends++;assert.equal(url,'https://provider.test/message/sendText/Teste');assert.equal(JSON.parse(options.body).text,JSON.parse(prepared.message).text);return Response.json({key:{id:'provider-confirmed'}})};
await Promise.all([call('/api/queue/tick','POST',{}),call('/api/queue/tick','POST',{})]);assert.equal(sends,1);
assert.equal((await (await call('/api/queue')).json()).entries.length,0);
assert.equal((await (await call('/api/contacts')).json()).contacts.length,0);
const sent=(await (await call('/api/history')).json()).entries.find(x=>x.id===prepared.id);assert.equal(sent.contactId,contact.id);assert.equal(sent.message,JSON.parse(prepared.message).text);assert.equal(sent.responsible,'Fernando');assert.equal(sent.status,'sent');
// A failed request stays out of sent history and pauses to prevent automatic duplicates.
await call('/api/contacts/import','POST',{city:'Teste',contacts:[{company:'Falha',phone:'13988888888'}]});
contact=(await (await call('/api/contacts')).json()).contacts[0];await call('/api/queue','POST',{contactIds:[contact.id]});await call('/api/queue/prepare','POST',{type:'initial'});sqlite.exec('UPDATE instances SET rest_until=NULL');await call('/api/queue/control','POST',{action:'START'});
globalThis.fetch=async()=>Response.json({error:'rejected'},{status:500});await call('/api/queue/tick','POST',{});
assert.equal((await (await call('/api/queue')).json()).entries[0].status,'ERROR');assert.equal((await (await call('/api/send-rules')).json()).rules.queue_state,'PAUSED');
assert(!(await (await call('/api/history')).json()).entries.some(x=>x.company==='Falha'));globalThis.fetch=originalFetch;
console.log('Edição, envio, exclusão da agenda ativa, vínculo de cadastro, concorrência e falhas verificados.');
// Exercise Agenda click handlers as well as the API, without sending any message.
vm.runInContext("renderAgenda=async()=>{};renderDashboard=async()=>{};showTab=tab=>{globalThis.lastTab=tab}",context);
let selected=[];context.document.querySelectorAll=()=>selected;
fields['queue-quantity'].value='1';fields['agenda-city'].value='Teste';fields['agenda-search'].value='';
await call('/api/contacts/import','POST',{city:'Teste',contacts:[{company:'Botão quantidade',phone:'13977777777'},{company:'Botão seleção',phone:'13966666666'}]});
await fields['add-queue'].click();assert.equal(context.lastTab,'queue');assert.equal(fields['add-queue'].disabled,false);assert(fields['agenda-status'].textContent.includes('1 contato'));
const selectable=(await (await call('/api/contacts')).json()).contacts.find(x=>x.status==='AGENDA');selected=[{value:selectable.id}];await fields['add-queue'].click();assert((await (await call('/api/queue')).json()).entries.some(x=>x.contact_id===selectable.id));
const card=make();fields.agenda.querySelector=()=>card;const oldCreate=context.document.createElement;context.document.createElement=()=>{const el=oldCreate();el.remove=()=>{};el.scrollIntoView=()=>{};return el};
context.editContact=selectable;vm.runInContext('openAgendaEditor(editContact)',context);const form=fields['agenda-editor'];assert.equal(form.children.length,9);const formInputs=form.children.slice(1,6).map(label=>label.children[0]);assert.equal(formInputs.length,5);formInputs[0].value='Empresa corrigida pelo formulário';formInputs[1].value='13966666666';formInputs[2].value='Cidade editada';formInputs[3].value='Responsável editado';formInputs[4].value='Observações editadas';await form.onsubmit({preventDefault(){}});
const edited=sqlite.prepare('SELECT * FROM contacts WHERE id=?').get(selectable.id);assert.equal(edited.company,formInputs[0].value);assert.equal(edited.city,formInputs[2].value);assert.equal(edited.responsible,formInputs[3].value);assert.equal(edited.notes,formInputs[4].value);
console.log('Cliques da Agenda: quantidade, seleção e edição dos cinco campos verificados.');
// Bot configuration fills and persists missing models while preserving custom messages.
await call('/api/settings','PUT',{config:{...config,templates:{initial:'Meu texto próprio',presentation:'',promotion:'',followup:'',trial:''},aiEnabled:true,aiDelaySeconds:0,aiRandomDelay:true,aiMinSeconds:0,aiMaxSeconds:0,aiTyping:true},apiKey:'bot-test-key'});
const botConfig=(await (await call('/api/settings')).json()).config;assert.equal(botConfig.templates.initial,'Meu texto próprio');for(const k of ['presentation','promotion','followup','trial'])assert(botConfig.templates[k].trim());assert.equal(botConfig.aiRandomDelay,true);assert.equal(botConfig.aiTyping,true);
assert.equal(JSON.parse(sqlite.prepare('SELECT config_json FROM settings').get().config_json).templates.trial,botConfig.templates.trial);
const botInstance=sqlite.prepare('SELECT * FROM instances LIMIT 1').get();let hookUrl,providerReplyCount=0,presenceCount=0;
globalThis.fetch=async(url,options)=>{if(url.includes('/webhook/set/')){hookUrl=JSON.parse(options.body).webhook.url;return Response.json({success:true})}if(url.includes('generativelanguage')){assert.equal(options.headers['x-goog-api-key'],'bot-test-key');return Response.json({candidates:[{content:{parts:[{text:JSON.stringify({reply:'Você pode testar por 30 dias. Posso conhecer seu estabelecimento?',interested:true})}]}}]})}if(url.includes('/chat/sendPresence/')){presenceCount++;return Response.json({success:true})}if(url.includes('/message/sendText/')){providerReplyCount++;return Response.json({key:{id:'reply-id'}})}throw new Error('Unexpected URL')};
response=await call('/api/instances/'+botInstance.id+'/bot','POST',{});assert.equal(response.status,200);assert(hookUrl.includes('/api/webhooks/'));assert.equal(sqlite.prepare('SELECT webhook_status FROM instances').get().webhook_status,'READY');
const incoming={event:'messages.upsert',data:{key:{id:'customer-message-1',remoteJid:'5513999999999@s.whatsapp.net',fromMe:false},pushName:'Cliente',message:{conversation:'Tenho interesse, como funciona?'},messageTimestamp:Math.floor(Date.now()/1000)}};
const hookPath=new URL(hookUrl).pathname;
async function webhook(payload,path=hookPath){return worker.fetch(new Request('https://example.com'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),env,{})}
assert.equal((await webhook(incoming,hookPath.slice(0,-1)+'x')).status,401);
response=await webhook(incoming);assert.equal(response.status,200);assert.equal(providerReplyCount,1);assert.equal(presenceCount,1);
await webhook(incoming);assert.equal(providerReplyCount,1);
let aiEntry=sqlite.prepare("SELECT * FROM ai_messages WHERE provider_message_id='customer-message-1'").get();assert.equal(aiEntry.status,'SENT');assert(aiEntry.reply.includes('30 dias'));assert.equal(sqlite.prepare('SELECT interested FROM contacts WHERE id=?').get(aiEntry.contact_id).interested,1);
assert((await (await call('/api/history')).json()).entries.some(x=>x.id===aiEntry.id&&x.contactId===aiEntry.contact_id&&x.message===aiEntry.reply));
const outgoing=structuredClone(incoming);outgoing.data.key.fromMe=true;outgoing.data.key.id='sent-echo';await webhook(outgoing);assert.equal(providerReplyCount,1);
const group=structuredClone(incoming);group.data.key.remoteJid='123@g.us';group.data.key.id='group-message';await webhook(group);assert.equal(providerReplyCount,1);
await call('/api/contacts/'+aiEntry.contact_id+'/ai','PATCH',{paused:true});const paused=structuredClone(incoming);paused.data.key.id='paused-message';await webhook(paused);assert.equal(providerReplyCount,1);
await call('/api/contacts/'+aiEntry.contact_id+'/ai','PATCH',{paused:false});await call('/api/settings','PUT',{config:{...botConfig,aiEnabled:false}});paused.data.key.id='global-off';await webhook(paused);assert.equal(providerReplyCount,1);
await call('/api/settings','PUT',{config:{...botConfig,aiEnabled:true}});globalThis.fetch=async(url)=>url.includes('generativelanguage')?Response.json({error:'quota'},{status:429}):Response.json({success:true});paused.data.key.id='quota-message';await webhook(paused);assert.equal(sqlite.prepare("SELECT status FROM ai_messages WHERE provider_message_id='quota-message'").get().status,'ERROR');
globalThis.fetch=originalFetch;
console.log('IA: padrões persistidos, webhook autenticado, resposta contextual, digitando, histórico, duplicidade, pausas, grupos e quota verificados.');
// GO uses its token, webhook subscription and the native presence field 'state'.
await call('/api/instances','POST',{name:'GO',provider:'EVOLUTION_GO',apiUrl:'https://go.test',token:'mock-admin',minSeconds:5,maxSeconds:5});const goInstance=sqlite.prepare("SELECT * FROM instances WHERE name='GO'").get();let goHook,goReplies=0;
globalThis.fetch=async(url,options)=>{const body=JSON.parse(options.body);if(url.endsWith('/instance/connect')){goHook=body.webhookUrl;assert.deepEqual(body.subscribe,['MESSAGE','CONNECTION']);assert.notEqual(options.headers.apikey,'mock-admin');return Response.json({message:'success'})}if(url.includes('generativelanguage'))return Response.json({candidates:[{content:{parts:[{text:'{"reply":"Olá! Posso explicar a Delivale?","interested":false}'}]}}]});if(url.endsWith('/message/presence')){assert.equal(body.state,'composing');return Response.json({message:'success'})}if(url.endsWith('/send/text')){goReplies++;return Response.json({message:'success'})}throw new Error('Unexpected GO endpoint')};
assert.equal((await call('/api/instances/'+goInstance.id+'/bot','POST',{})).status,200);
await webhook({event:'Message',data:{Info:{ID:'go-incoming',Chat:'5513999999999@s.whatsapp.net',IsFromMe:false},Message:{conversation:'Olá'}}},new URL(goHook).pathname);assert.equal(goReplies,1);globalThis.fetch=originalFetch;
const botSource=fs.readFileSync('worker/bot.js','utf8');const timingContext={TEMPLATE_KEYS:['initial','presentation','promotion','followup','trial']};vm.createContext(timingContext);vm.runInContext(botSource,timingContext);assert.equal(vm.runInContext('botDelay(completeBotConfig({aiDelaySeconds:5}))',timingContext),5000);for(let i=0;i<20;i++){const delay=vm.runInContext('botDelay(completeBotConfig({aiRandomDelay:true,aiMinSeconds:1,aiMaxSeconds:5}))',timingContext);assert(delay>=1000&&delay<=5000)}
console.log('Evolution GO, presença e tempo fixo/aleatório verificados.');
// Live status follows the provider, including auth/transient failure rather than stale Online.
globalThis.fetch=async(url)=>url.startsWith('https://go.test')?Response.json({data:{connected:true,loggedIn:true}}):Response.json({instance:{state:'open'}});
response=await call('/api/instances/refresh','POST',{});assert.equal(response.status,200);assert((await response.json()).instances.every(x=>x.status==='CONNECTED'));
globalThis.fetch=async()=>Response.json({data:{connected:true,loggedIn:false}});await call('/api/instances/'+goInstance.id+'/status','POST',{});assert.equal(sqlite.prepare('SELECT status FROM instances WHERE id=?').get(goInstance.id).status,'DISCONNECTED');
globalThis.fetch=async()=>Response.json({error:'unavailable'},{status:503});await call('/api/instances/'+botInstance.id+'/status','POST',{});assert.equal(sqlite.prepare('SELECT status FROM instances WHERE id=?').get(botInstance.id).status,'UNKNOWN');
// Connection webhooks remain active while the conversation bot is off.
await call('/api/settings','PUT',{config:{...botConfig,aiEnabled:false}});await webhook({event:'connection.update',data:{state:'open'}});assert.equal(sqlite.prepare('SELECT status FROM instances WHERE id=?').get(botInstance.id).status,'CONNECTED');await webhook({event:'Disconnected'},new URL(goHook).pathname);assert.equal(sqlite.prepare('SELECT status FROM instances WHERE id=?').get(goInstance.id).status,'DISCONNECTED');
const pending=sqlite.prepare("SELECT id FROM ai_messages WHERE instance_id=? LIMIT 1").get(botInstance.id);sqlite.prepare("UPDATE ai_messages SET status='PROCESSING' WHERE id=?").run(pending.id);assert.equal((await call('/api/instances/'+botInstance.id,'DELETE',{})).status,409);sqlite.prepare("UPDATE ai_messages SET status='SENT' WHERE id=?").run(pending.id);
assert.equal((await call('/api/instances/'+botInstance.id,'DELETE',{})).status,200);assert(!sqlite.prepare('SELECT id FROM instances WHERE id=?').get(botInstance.id));assert(sqlite.prepare('SELECT id FROM sends WHERE id=?').get(pending.id));globalThis.fetch=originalFetch;
console.log('Status online/offline/indisponível, eventos de conexão e exclusão com histórico preservado verificados.');
// Cloud previews returning HTML for /api must use the shared backend.
let previewRequests=[];context.fetch=async(path,options={})=>{previewRequests.push(path);if(path.startsWith('/'))return new Response('<html>Preview</html>',{headers:{'Content-Type':'text/html'}});return call(new URL(path).pathname,options.method||'GET',options.body?JSON.parse(options.body):undefined)};
await vm.runInContext("apiCall('/api/settings')",context);assert.equal(previewRequests[0],'/api/settings');assert(previewRequests[1].startsWith('https://'));await vm.runInContext("apiCall('/api/send-rules')",context);assert(previewRequests.at(-1).startsWith('https://'));
const previewOrigin='https://enviozap-example.run.app';let cors=await worker.fetch(new Request('https://example.com/api/settings',{method:'OPTIONS',headers:{Origin:previewOrigin,'Access-Control-Request-Method':'PUT'}}),env,{});assert.equal(cors.status,204);assert.equal(cors.headers.get('Access-Control-Allow-Origin'),previewOrigin);
cors=await worker.fetch(new Request('https://example.com/api/settings',{method:'PUT',headers:{Origin:previewOrigin,'Content-Type':'application/json'},body:JSON.stringify({config})}),env,{});assert.equal(cors.status,200);assert.equal(cors.headers.get('Access-Control-Allow-Origin'),previewOrigin);assert.equal((await worker.fetch(new Request('https://example.com/api/settings',{method:'OPTIONS',headers:{Origin:'https://untrusted.test'}}),env,{})).status,403);
console.log('HTML sem API, backend alternativo e CORS de prévia/Cloud Run verificados.');
