import fs from 'node:fs';import {DatabaseSync} from 'node:sqlite';import assert from 'node:assert/strict';import vm from 'node:vm';import {randomUUID} from 'node:crypto';
const sqlite=new DatabaseSync(':memory:');sqlite.exec(fs.readFileSync('drizzle/0000_bent_hydra.sql','utf8'));
const DB={prepare(sql){const stmt=sqlite.prepare(sql);return{bind(...args){return{async first(){return stmt.get(...args)||null},async all(){return{results:stmt.all(...args)}},async run(){return{meta:stmt.run(...args)}}}}}}};
const {default:worker}=await import('data:text/javascript;base64,'+Buffer.from(fs.readFileSync('worker/index.js','utf8')).toString('base64'));
const env={DB,SETTINGS_ENCRYPTION_KEY:'01'.repeat(32)};
async function call(path,method='GET',data){return worker.fetch(new Request('https://example.com'+path,{method,headers:{Origin:'https://example.com'},...(data?{body:JSON.stringify(data)}:{})}),env,{})}
const config={offer:'Cardápio digital e 30 dias grátis',tone:'Natural',length:'Curta',emojis:true,templates:{initial:'Oi {empresa}',presentation:'Apresentação',promotion:'Promoção',followup:'Retorno',trial:'Teste'}};
assert.equal((await (await call('/api/settings')).json()).config,null);
let response=await call('/api/settings','PUT',{config,apiKey:'test-only-key'});assert.equal(response.status,200);let settings=await response.json();assert.equal(settings.hasApiKey,true);assert(!JSON.stringify(settings).includes('test-only-key'));assert(!sqlite.prepare('SELECT key_cipher FROM settings').get().key_cipher.includes('test-only-key'));
await call('/api/settings','PUT',{config:{...config,offer:'Nova oferta'},initializeOnly:true});assert.equal((await (await call('/api/settings')).json()).config.offer,config.offer);
const originalFetch=globalThis.fetch;globalThis.fetch=async(url,options)=>{assert.equal(options.headers['x-goog-api-key'],'test-only-key');return Response.json({candidates:[{content:{parts:[{text:'Texto criado'}]}}]})};response=await call('/api/generate-message','POST',{company:'Empresa',niche:'Delivery',goal:'Apresentar um serviço',tone:'Natural',length:'Curta',emojis:true,details:config.offer,current:'Oi'});assert.equal((await response.json()).message,'Texto criado');globalThis.fetch=originalFetch;
const entry={id:randomUUID(),company:'Loja Teste',phone:'5513991424545',message:'Olá',type:'Mensagem inicial',date:new Date().toISOString()};await call('/api/history','POST',entry);await call('/api/history','POST',entry);let list=(await (await call('/api/history')).json()).entries;assert.equal(list.length,1);assert.equal(list[0].status,'opened');await call('/api/history/'+entry.id,'PATCH',{});assert.equal((await (await call('/api/history')).json()).entries[0].status,'sent');
const html=fs.readFileSync('worker/page.html','utf8');const fields={};const make=()=>({value:'',hidden:false,checked:false,children:[],classList:{toggle(){}},addEventListener(e,f){this[e]=f},focus(){},setAttribute(){},replaceChildren(){this.children=[]},append(...a){this.children.push(...a)},select(){},setSelectionRange(){}});for(const m of html.matchAll(/id="([^"]+)"/g))fields[m[1]]=make();fields.type.value='initial';fields.niche.value='Delivery';fields.output.hidden=true;
const context={structuredClone,crypto:{randomUUID},confirm:()=>true,document:{getElementById:id=>fields[id],createElement(){const el=make();Object.defineProperty(el,'id',{set(id){fields[id]=el}});return el}},localStorage:{getItem(){return null},removeItem(){}},navigator:{},fetch:(path,options={})=>call(path,options.method||'GET',options.body?JSON.parse(options.body):undefined)};
vm.createContext(context);vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],context);await vm.runInContext('initializeDatabase()',context);assert.equal(fields.offer.value,config.offer);assert(fields['key-saved-status'].textContent.includes('salva'));fields.offer.value='Oferta em outra máquina';await fields['save-settings'].click();assert.equal((await (await call('/api/settings')).json()).config.offer,'Oferta em outra máquina');await vm.runInContext('renderHistory()',context);assert.equal(fields['history-rows'].children.length,1);assert(fields['history-rows'].children[0].children[3].textContent.includes('Enviado'));
fields['api-key'].value='replacement-test-key';await fields['save-key'].click();assert.equal(fields['api-key'].value,'');assert(fields['key-saved-status'].textContent.includes('salva'));const unchanged=(await (await call('/api/settings')).json()).config;assert.equal(unchanged.offer,'Oferta em outra máquina');assert.equal(fields['save-key'].disabled,false);
await call('/api/settings','PUT',{config,removeApiKey:true});assert.equal((await (await call('/api/settings')).json()).hasApiKey,false);
console.log('Banco compartilhado, criptografia da chave, leitura sem exposição, histórico idempotente e interface verificados.');
