import {sql} from 'drizzle-orm';
import {sqliteTable,text,integer,uniqueIndex,index} from 'drizzle-orm/sqlite-core';
export const settings=sqliteTable('settings',{id:integer('id').primaryKey(),configJson:text('config_json').notNull(),keyCipher:text('key_cipher'),updatedAt:text('updated_at').notNull()});
export const sends=sqliteTable('sends',{id:text('id').primaryKey(),company:text('company').notNull(),phone:text('phone').notNull(),message:text('message').notNull(),type:text('type').notNull(),openedAt:text('opened_at').notNull(),status:text('status').notNull().default('opened'),confirmedAt:text('confirmed_at')});
export const contacts=sqliteTable('contacts',{id:text('id').primaryKey(),company:text('company').notNull(),responsible:text('responsible'),phone:text('phone').notNull(),city:text('city').notNull(),notes:text('notes'),aiPaused:integer('ai_paused').notNull().default(0),status:text('status').notNull().default('AGENDA'),interested:integer('interested',{mode:'boolean'}).notNull().default(false),createdAt:text('created_at').notNull(),importedAt:text('imported_at'),lastSentAt:text('last_sent_at'),lastInstance:text('last_instance')},t=>[uniqueIndex('contacts_phone_unique').on(t.phone),index('contacts_city_status_idx').on(t.city,t.status)]);
export const queue=sqliteTable('send_queue',{id:text('id').primaryKey(),contactId:text('contact_id').notNull(),status:text('status').notNull().default('QUEUED'),position:integer('position').notNull(),message:text('message'),instanceName:text('instance_name'),createdAt:text('created_at').notNull(),processingAt:text('processing_at'),sentAt:text('sent_at'),error:text('error')},t=>[uniqueIndex('send_queue_active_contact_unique').on(t.contactId).where(sql`${t.status} IN ('QUEUED','PROCESSING')`)]);
export const contactEvents=sqliteTable('contact_events',{id:text('id').primaryKey(),contactId:text('contact_id').notNull(),event:text('event').notNull(),details:text('details'),createdAt:text('created_at').notNull()},t=>[index('contact_events_contact_idx').on(t.contactId,t.createdAt)]);
export const sendRules=sqliteTable('send_rules',{id:integer('id').primaryKey(),minSeconds:integer('min_seconds').notNull().default(60),maxSeconds:integer('max_seconds').notNull().default(180),messagesPerCycle:integer('messages_per_cycle').notNull().default(10),restMinutes:integer('rest_minutes').notNull().default(20),switchAfter:integer('switch_after').notNull().default(10),queueState:text('queue_state').notNull().default('PAUSED'),updatedAt:text('updated_at').notNull()});
export const instances=sqliteTable('instances',{id:text('id').primaryKey(),name:text('name').notNull(),status:text('status').notNull().default('DISCONNECTED'),provider:text('provider').notNull().default('EVOLUTION_API'),apiUrl:text('api_url'),tokenCipher:text('token_cipher'),instanceTokenCipher:text('instance_token_cipher'),webhookTokenCipher:text('webhook_token_cipher'),webhookStatus:text('webhook_status').notNull().default('PENDING'),lastCheckedAt:text('last_checked_at'),restUntil:text('rest_until'),sentInCycle:integer('sent_in_cycle').notNull().default(0),minSeconds:integer('min_seconds').notNull().default(60),maxSeconds:integer('max_seconds').notNull().default(180),messagesPerCycle:integer('messages_per_cycle').notNull().default(10),restMinutes:integer('rest_minutes').notNull().default(20),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()});

export const aiMessages=sqliteTable('ai_messages',{id:text('id').primaryKey(),instanceId:text('instance_id').notNull(),contactId:text('contact_id').notNull(),providerMessageId:text('provider_message_id').notNull(),incoming:text('incoming').notNull(),reply:text('reply'),status:text('status').notNull().default('RECEIVED'),error:text('error'),createdAt:text('created_at').notNull(),sentAt:text('sent_at')},t=>[uniqueIndex('ai_message_provider_unique').on(t.instanceId,t.providerMessageId),index('ai_message_contact_idx').on(t.contactId,t.createdAt)]);
