function database(env){if(!env.DB)throw new Error('DB_UNAVAILABLE');return env.DB}
function statement(env,sql,...values){return database(env).prepare(sql).bind(...values)}
async function savedSettings(env){return statement(env,'SELECT config_json,key_cipher FROM settings WHERE id = ?',1).first()}
async function encryptionKey(env){if(!env.SETTINGS_ENCRYPTION_KEY)throw new Error('KEY_CONFIG_UNAVAILABLE');return crypto.subtle.importKey('raw',Uint8Array.from(env.SETTINGS_ENCRYPTION_KEY.match(/.{2}/g).map(v=>parseInt(v,16))),{name:'AES-GCM'},false,['encrypt','decrypt'])}
function base64(bytes){return btoa(String.fromCharCode(...new Uint8Array(bytes)))}
function fromBase64(s){return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
async function encryptSecret(secret,env){const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},await encryptionKey(env),new TextEncoder().encode(secret));return base64(iv)+'.'+base64(data)}
async function decryptSecret(cipher,env){const [iv,data]=cipher.split('.');return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:fromBase64(iv)},await encryptionKey(env),fromBase64(data)))}
async function configuredApiKey(env){const row=await savedSettings(env);return row?.key_cipher?decryptSecret(row.key_cipher,env):env.GEMINI_API_KEY||''}
const TEMPLATE_KEYS=['initial','presentation','promotion','followup','trial'];
function validConfig(config){return config&&typeof config.aiEnabled==='boolean'&&typeof config.aiInstructions==='string'&&config.aiInstructions.length<=8000&&typeof config.aiRegistration==='string'&&config.aiRegistration.length<=4000&&typeof config.aiHandoff==='string'&&config.aiHandoff.length<=3000&&typeof config.offer==='string'&&config.offer.trim()&&config.offer.length<=4000&&typeof config.tone==='string'&&config.tone.length<=100&&typeof config.length==='string'&&config.length.length<=50&&typeof config.emojis==='boolean'&&TEMPLATE_KEYS.every(k=>typeof config.templates?.[k]==='string'&&config.templates[k].length<=10000)}
async function requestData(request,max=75000){const raw=await request.text();if(raw.length>max)throw new Error('INPUT_TOO_LARGE');return JSON.parse(raw)}
function cleanPhone(v){let d=String(v||'').replace(/\D/g,'');if(d.length===10||d.length===11)d='55'+d;return d}
function cleanText(v,max=200){return String(v||'').trim().slice(0,max)}
async function event(env,contactId,name,details=''){await statement(env,'INSERT INTO contact_events(id,contact_id,event,details,created_at) VALUES(?,?,?,?,?)',crypto.randomUUID(),contactId,name,details,new Date().toISOString()).run()}
async function handleStorage(request,env,url){
 const central=url.pathname.startsWith('/api/contacts')||url.pathname.startsWith('/api/queue')||url.pathname==='/api/dashboard'||url.pathname==='/api/send-rules'||url.pathname.startsWith('/api/instances');
 if(!central&&!['/api/settings','/api/settings/key','/api/history'].includes(url.pathname)&&!url.pathname.startsWith('/api/history/'))return null;
 if(request.method!=='GET'&&request.headers.get('Origin')!==url.origin)return json({error:'Origem não autorizada.'},403);
 try{
  if(central)await statement(env,"INSERT OR IGNORE INTO send_rules(id,updated_at) VALUES(1,?)",new Date().toISOString()).run();
  if(url.pathname==='/api/dashboard'&&request.method==='GET'){
   const [agenda,queued,sent,interested,errors]=await Promise.all([
    statement(env,"SELECT COUNT(*) n FROM contacts WHERE status='AGENDA'").first(),
    statement(env,"SELECT COUNT(*) n FROM send_queue WHERE status IN ('QUEUED','PROCESSING')").first(),
    statement(env,"SELECT COUNT(*) n FROM contacts WHERE status='SENT' OR status='INTERESTED'").first(),
    statement(env,"SELECT COUNT(*) n FROM contacts WHERE interested=1").first(),
    statement(env,"SELECT COUNT(*) n FROM send_queue WHERE status='ERROR'").first()
   ]);return json({agenda:agenda?.n||0,queued:queued?.n||0,sent:sent?.n||0,interested:interested?.n||0,errors:errors?.n||0})
  }
  if(url.pathname==='/api/contacts'&&request.method==='GET'){
   const city=cleanText(url.searchParams.get('city')||'',120),status=cleanText(url.searchParams.get('status')||'',30),q=cleanText(url.searchParams.get('q')||'',150);
   let sql="SELECT * FROM contacts WHERE status IN ('AGENDA','QUEUED')",args=[];if(city){sql+=' AND city=?';args.push(city)}if(status){sql+=' AND status=?';args.push(status)}if(q){sql+=' AND (company LIKE ? OR phone LIKE ? OR city LIKE ?)';args.push('%'+q+'%','%'+q+'%','%'+q+'%')}sql+=' ORDER BY company COLLATE NOCASE';
   const result=await statement(env,sql,...args).all();const cities=await statement(env,'SELECT DISTINCT city FROM contacts ORDER BY city COLLATE NOCASE').all();return json({contacts:result.results||[],cities:(cities.results||[]).map(x=>x.city)})
  }
  if(url.pathname==='/api/contacts/import'&&request.method==='POST'){
   const data=await requestData(request,200000);const city=cleanText(data.city,120);if(!city||!Array.isArray(data.contacts)||!data.contacts.length)return json({error:'Informe a cidade e os contatos.'},400);
   let imported=0,skipped=0;for(const item of data.contacts.slice(0,5000)){const company=cleanText(item.company||item.name,150),phone=cleanPhone(item.phone||item.whatsapp);if(!company||!/^[0-9]{10,15}$/.test(phone)){skipped++;continue}const id=crypto.randomUUID(),now=new Date().toISOString();const r=await statement(env,'INSERT OR IGNORE INTO contacts(id,company,responsible,phone,city,notes,status,interested,created_at,imported_at) VALUES(?,?,?,?,?,?,?,?,?,?)',id,company,cleanText(item.responsible,150),phone,city,cleanText(item.notes,1000),'AGENDA',0,now,now).run();if(r.meta?.changes){imported++;await event(env,id,'IMPORTED','Cidade: '+city)}else skipped++}return json({success:true,imported,skipped})
  }
  if(url.pathname.match(/^\/api\/contacts\/[^/]+$/)&&request.method==='PATCH'){
   const id=decodeURIComponent(url.pathname.split('/').pop()),data=await requestData(request,10000);const company=cleanText(data.company,150),phone=cleanPhone(data.phone),city=cleanText(data.city,120);if(!company||!city||!/^[0-9]{10,15}$/.test(phone))return json({error:'Confira estabelecimento, WhatsApp e cidade.'},400);
   const r=await statement(env,'UPDATE contacts SET company=?,responsible=?,phone=?,city=?,notes=? WHERE id=?',company,cleanText(data.responsible,150),phone,city,cleanText(data.notes,1000),id).run();if(r.meta?.changes)await event(env,id,'EDITED');return r.meta?.changes?json({success:true}):json({error:'Contato não encontrado.'},404)
  }
  if(url.pathname.match(/^\/api\/contacts\/[^/]+\/interest$/)&&request.method==='PATCH'){
   const id=decodeURIComponent(url.pathname.split('/')[3]),data=await requestData(request,1000),value=data.interested===true;const r=await statement(env,"UPDATE contacts SET interested=?,status=CASE WHEN ?=1 THEN 'INTERESTED' ELSE CASE WHEN last_sent_at IS NULL THEN 'AGENDA' ELSE 'SENT' END END WHERE id=?",value?1:0,value?1:0,id).run();if(r.meta?.changes)await event(env,id,value?'INTERESTED':'INTEREST_REMOVED');return r.meta?.changes?json({success:true}):json({error:'Contato não encontrado.'},404)
  }
  if(url.pathname.match(/^\/api\/contacts\/[^/]+\/return$/)&&request.method==='POST'){
   const id=decodeURIComponent(url.pathname.split('/')[3]);const r=await statement(env,"UPDATE contacts SET status='AGENDA' WHERE id=?",id).run();if(r.meta?.changes)await event(env,id,'RETURNED_TO_AGENDA');return r.meta?.changes?json({success:true}):json({error:'Contato não encontrado.'},404)
  }
  if(url.pathname==='/api/queue'&&request.method==='GET'){const r=await statement(env,"SELECT q.*,c.company,c.phone,c.city,c.interested FROM send_queue q JOIN contacts c ON c.id=q.contact_id WHERE q.status IN ('QUEUED','PROCESSING','ERROR') ORDER BY q.position,q.created_at").all();return json({entries:r.results||[]})}
  if(url.pathname==='/api/queue'&&request.method==='DELETE'){
   const rows=(await statement(env,"SELECT id,contact_id FROM send_queue WHERE status IN ('QUEUED','ERROR')").all()).results||[];
   for(const row of rows){await statement(env,'DELETE FROM send_queue WHERE id=?',row.id).run();await statement(env,"UPDATE contacts SET status='AGENDA' WHERE id=?",row.contact_id).run();await event(env,row.contact_id,'QUEUE_CLEARED')}
   return json({success:true,cleared:rows.length})
  }
  if(url.pathname==='/api/queue'&&request.method==='POST'){
   const data=await requestData(request,20000),limit=Math.max(1,Math.min(500,Number(data.quantity)||1)),city=cleanText(data.city,120),q=cleanText(data.q,150);let contacts=[];if(Array.isArray(data.contactIds)&&data.contactIds.length){for(const id of data.contactIds.slice(0,500)){const c=await statement(env,"SELECT id,last_sent_at FROM contacts WHERE id=? AND status='AGENDA'",cleanText(id,100)).first();if(c)contacts.push(c)}}else{let sql="SELECT id,last_sent_at FROM contacts WHERE status='AGENDA'",args=[];if(city){sql+=' AND city=?';args.push(city)}if(q){sql+=' AND (company LIKE ? OR phone LIKE ? OR city LIKE ?)';args.push('%'+q+'%','%'+q+'%','%'+q+'%')}sql+=' ORDER BY company COLLATE NOCASE LIMIT ?';args.push(limit);contacts=(await statement(env,sql,...args).all()).results||[]}let added=0;const pos=await statement(env,'SELECT COALESCE(MAX(position),0) n FROM send_queue').first();let position=Number(pos?.n||0);for(const c of contacts){if(c.last_sent_at&&!data.allowResend)continue;const id=crypto.randomUUID();try{await statement(env,"INSERT INTO send_queue(id,contact_id,status,position,created_at) VALUES(?,?,'QUEUED',?,?)",id,c.id,++position,new Date().toISOString()).run();await statement(env,"UPDATE contacts SET status='QUEUED' WHERE id=?",c.id).run();await event(env,c.id,'QUEUED');added++}catch{}}return json({success:true,added})
  }
  if(url.pathname==='/api/queue/prepare'&&request.method==='POST'){const data=await requestData(request,10000),type=TEMPLATE_KEYS.includes(data.type)?data.type:'initial',mode=data.mode==='AI'?'AI':'STANDARD',settings=await savedSettings(env);if(!settings)return json({error:'Configure as mensagens primeiro.'},409);const config=JSON.parse(settings.config_json),rows=(await statement(env,"SELECT q.id,c.company FROM send_queue q JOIN contacts c ON c.id=q.contact_id WHERE q.status='QUEUED' ORDER BY q.position").all()).results||[];let prepared=0;for(const row of rows){let message=String(config.templates?.[type]||'').replaceAll('{empresa}',row.company);if(mode==='AI'){const response=await generateQueueMessage(env,url,config,row.company,message);message=response}message=resolveSpintax(message);if(!message.trim())return json({error:'O modelo de mensagem está vazio.'},409);await statement(env,'UPDATE send_queue SET message=? WHERE id=?',JSON.stringify({mode,type,text:message}),row.id).run();prepared++}return json({success:true,prepared,mode,type})}
  if(url.pathname.match(/^\/api\/queue\/[^/]+$/)&&request.method==='DELETE'){const id=decodeURIComponent(url.pathname.split('/').pop());const row=await statement(env,'SELECT contact_id FROM send_queue WHERE id=? AND status=?',id,'QUEUED').first();if(!row)return json({error:'Item não pode ser removido.'},409);await statement(env,'DELETE FROM send_queue WHERE id=?',id).run();await statement(env,"UPDATE contacts SET status='AGENDA' WHERE id=?",row.contact_id).run();await event(env,row.contact_id,'QUEUE_REMOVED');return json({success:true})}
  if(url.pathname==='/api/queue/control'&&request.method==='POST'){const d=await requestData(request,2000),action=String(d.action||'').toUpperCase(),map={START:'RUNNING',RESUME:'RUNNING',PAUSE:'PAUSED',STOP:'STOPPED'};if(!map[action])return json({error:'Ação inválida.'},400);if(action==='START'||action==='RESUME'){const unprepared=await statement(env,"SELECT COUNT(*) n FROM send_queue WHERE status='QUEUED' AND (message IS NULL OR message='')").first();if(unprepared?.n)return json({error:'Prepare as mensagens antes de iniciar.'},409);const queued=await statement(env,"SELECT COUNT(*) n FROM send_queue WHERE status='QUEUED'").first();if(!(queued?.n>0))return json({error:'Não há contatos aguardando envio.'},409);const connected=await statement(env,"SELECT COUNT(*) n FROM instances WHERE status='CONNECTED'").first();if(!(connected?.n>0))return json({error:'Conecte pelo menos uma instância antes de iniciar.'},409)}await statement(env,'UPDATE send_rules SET queue_state=?,updated_at=? WHERE id=1',map[action],new Date().toISOString()).run();const message=map[action]==='RUNNING'?'Fila iniciada.':map[action]==='PAUSED'?'Fila pausada.':'Fila parada.';return json({success:true,state:map[action],message})}
  if(url.pathname==='/api/queue/tick'&&request.method==='POST')return json(await processQueue(env));
  if(url.pathname==='/api/send-rules'){
   if(request.method==='GET'){const r=await statement(env,'SELECT * FROM send_rules WHERE id=1').first();return json({rules:r,...await queueTiming(env)})}
   if(request.method==='PUT'){const d=await requestData(request,5000),min=Math.max(1,Number(d.minSeconds)||60),max=Math.max(min,Number(d.maxSeconds)||180),cycle=Math.max(1,Number(d.messagesPerCycle)||10),rest=Math.max(0,Number(d.restMinutes)||20),sw=Math.max(1,Number(d.switchAfter)||10);await statement(env,'UPDATE send_rules SET min_seconds=?,max_seconds=?,messages_per_cycle=?,rest_minutes=?,switch_after=?,updated_at=? WHERE id=1',min,max,cycle,rest,sw,new Date().toISOString()).run();return json({success:true})}
  }
  if(url.pathname==='/api/instances'&&request.method==='GET'){const r=await statement(env,'SELECT id,name,status,COALESCE(provider,\'EVOLUTION_API\') AS provider,api_url AS apiUrl,last_checked_at AS lastCheckedAt,rest_until AS restUntil,sent_in_cycle AS sentInCycle,min_seconds AS minSeconds,max_seconds AS maxSeconds,messages_per_cycle AS messagesPerCycle,rest_minutes AS restMinutes,webhook_status AS webhookStatus FROM instances ORDER BY name').all();return json({instances:r.results||[]})}
  if(url.pathname==='/api/instances'&&request.method==='POST'){const d=await requestData(request,7000),provider=d.provider==='EVOLUTION_GO'?'EVOLUTION_GO':'EVOLUTION_API',name=cleanText(d.name,100),apiUrl=cleanText(d.apiUrl,500).replace(/\/$/,'');const token=String(d.token||'').trim(),minSeconds=Math.max(1,Number(d.minSeconds)||60),maxSeconds=Math.max(minSeconds,Number(d.maxSeconds)||180),messagesPerCycle=Math.max(1,Number(d.messagesPerCycle)||10),restMinutes=Math.max(0,Number(d.restMinutes)||20);if(!name||!apiUrl||!token)return json({error:'Informe serviço, nome, URL e API Key.'},400);const instanceToken=provider==='EVOLUTION_GO'?Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join(''):'';const id=crypto.randomUUID(),now=new Date().toISOString();await statement(env,"INSERT INTO instances(id,name,status,provider,api_url,token_cipher,instance_token_cipher,min_seconds,max_seconds,messages_per_cycle,rest_minutes,created_at,updated_at) VALUES(?,?,'DISCONNECTED',?,?,?,?,?,?,?,?,?,?)",id,name,provider,apiUrl,await encryptSecret(token,env),instanceToken?await encryptSecret(instanceToken,env):null,minSeconds,maxSeconds,messagesPerCycle,restMinutes,now,now).run();return json({success:true,id})}
  if(url.pathname.match(/^\/api\/instances\/[^/]+$/)&&request.method==='PATCH'){const id=decodeURIComponent(url.pathname.split('/')[3]),row=await statement(env,'SELECT * FROM instances WHERE id=?',id).first();if(!row)return json({error:'Instância não encontrada.'},404);const d=await requestData(request,7000),provider=d.provider==='EVOLUTION_GO'?'EVOLUTION_GO':'EVOLUTION_API',name=cleanText(d.name,100),apiUrl=cleanText(d.apiUrl,500).replace(/\/$/,'');const token=String(d.token||'').trim(),minSeconds=Math.max(1,Number(d.minSeconds)||row.min_seconds||60),maxSeconds=Math.max(minSeconds,Number(d.maxSeconds)||row.max_seconds||180),messagesPerCycle=Math.max(1,Number(d.messagesPerCycle)||row.messages_per_cycle||10),restMinutes=Math.max(0,Number(d.restMinutes)??row.rest_minutes??20);if(!name||!apiUrl)return json({error:'Informe serviço, nome e URL.'},400);let tokenCipher=row.token_cipher,instanceTokenCipher=row.instance_token_cipher;if(token)tokenCipher=await encryptSecret(token,env);if(provider==='EVOLUTION_GO'&&!instanceTokenCipher){const generated=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');instanceTokenCipher=await encryptSecret(generated,env)}await statement(env,"UPDATE instances SET name=?,provider=?,api_url=?,token_cipher=?,instance_token_cipher=?,min_seconds=?,max_seconds=?,messages_per_cycle=?,rest_minutes=?,status='DISCONNECTED',updated_at=? WHERE id=?",name,provider,apiUrl,tokenCipher,instanceTokenCipher,minSeconds,maxSeconds,messagesPerCycle,restMinutes,new Date().toISOString(),id).run();return json({success:true})}
    if(url.pathname.match(/^\/api\/instances\/[^/]+\/(connect|status)$/)&&request.method==='POST'){
   const parts=url.pathname.split('/'),id=decodeURIComponent(parts[3]),action=parts[4];const row=await statement(env,'SELECT * FROM instances WHERE id=?',id).first();if(!row)return json({error:'Instância não encontrada.'},404);if(!row.api_url||!row.token_cipher)return json({error:'Configure URL e API Key.'},400);
   let globalToken,instanceToken='';try{globalToken=await decryptSecret(row.token_cipher,env);if(row.instance_token_cipher)instanceToken=await decryptSecret(row.instance_token_cipher,env)}catch{return json({error:'Não foi possível abrir as credenciais salvas.'},503)}
   const hook=await webhookAddress(row,env,url.origin);const provider=row.provider||'EVOLUTION_API',base=String(row.api_url).replace(/\/$/,'');const call=async(path,key,options={})=>{const resp=await fetch(base+path,{...options,headers:{'Content-Type':'application/json','apikey':key,...(options.headers||{})},signal:AbortSignal.timeout(20000)});let data={};try{data=await resp.json()}catch{}return {ok:resp.ok,status:resp.status,data}};
   if(provider==='EVOLUTION_GO'){
    if(!instanceToken)return json({error:'Token da instância Evolution GO não configurado.'},400);
    if(action==='status'){const r=await call('/instance/status',instanceToken);const connected=!!(r.data?.data?.loggedIn??r.data?.loggedIn??r.data?.data?.connected??r.data?.connected);await statement(env,'UPDATE instances SET status=?,last_checked_at=?,updated_at=? WHERE id=?',connected?'CONNECTED':'DISCONNECTED',new Date().toISOString(),new Date().toISOString(),id).run();if(!r.ok)return json({error:r.data?.message||'Não foi possível consultar a Evolution GO.'},502);return json({success:true,connected})}
    const created=await call('/instance/create',globalToken,{method:'POST',body:JSON.stringify({name:row.name,token:instanceToken,webhook:hook,webhookEvents:['messages.upsert']})});if(!created.ok&&![400,409,422].includes(created.status))return json({error:created.data?.message||'Falha ao criar a instância na Evolution GO.'},502);
    const connected=await call('/instance/connect',instanceToken,{method:'POST',body:JSON.stringify({webhookUrl:hook,subscribe:['MESSAGE']})});if(!connected.ok&&![400,409,422].includes(connected.status))return json({error:connected.data?.message||'Falha ao iniciar conexão na Evolution GO.'},502);
    await statement(env,"UPDATE instances SET webhook_status='READY' WHERE id=?",id).run();await new Promise(r=>setTimeout(r,800));const qrRes=await call('/instance/qr',instanceToken);if(!qrRes.ok)return json({error:qrRes.data?.message||'Evolution GO não retornou o QR Code.'},502);const qr=qrRes.data?.data?.code||qrRes.data?.code||qrRes.data?.data?.qrcode||qrRes.data?.qrcode||null;return json({success:true,connected:false,qr})
   }
   if(action==='status'){const r=await call('/instance/connectionState/'+encodeURIComponent(row.name),globalToken);const state=String(r.data?.instance?.state||r.data?.state||'').toLowerCase(),connected=state==='open'||state==='connected';await statement(env,'UPDATE instances SET status=?,last_checked_at=?,updated_at=? WHERE id=?',connected?'CONNECTED':'DISCONNECTED',new Date().toISOString(),new Date().toISOString(),id).run();if(!r.ok)return json({error:r.data?.message||'Não foi possível consultar a Evolution API.'},502);return json({success:true,connected,state})}
   const created=await call('/instance/create',globalToken,{method:'POST',body:JSON.stringify({instanceName:row.name,qrcode:true,integration:'WHATSAPP-BAILEYS'})});if(!created.ok&&![400,403,409,422].includes(created.status))return json({error:created.data?.message||'Falha ao criar a instância na Evolution API.'},502);await configureBotWebhook({...row,webhook_token_cipher:(await statement(env,'SELECT webhook_token_cipher FROM instances WHERE id=?',row.id).first()).webhook_token_cipher},env,url.origin);const conn=await call('/instance/connect/'+encodeURIComponent(row.name),globalToken);if(!conn.ok)return json({error:conn.data?.message||'A Evolution API não retornou o QR Code.'},502);const qr=conn.data?.base64||conn.data?.qrcode?.base64||conn.data?.qr||conn.data?.code||created.data?.qrcode?.base64||created.data?.base64||null;return json({success:true,connected:false,qr})
  }
  if(url.pathname==='/api/settings/key'){
   if(request.method!=='PUT')return json({error:'Método não permitido.'},405);
   const data=await requestData(request,2500);const key=normalizeApiKey(data?.apiKey);if(!key||key.length>512)return json({error:'Insira a chave Gemini antes de salvar.'},400);
   const row=await savedSettings(env);if(!row)return json({error:'Aguarde as configurações carregarem e tente novamente.'},409);
   await statement(env,'UPDATE settings SET key_cipher = ?, updated_at = ? WHERE id = ?',await encryptSecret(key,env),new Date().toISOString(),1).run();return json({hasApiKey:true})
  }
  if(url.pathname==='/api/settings'){
   if(request.method==='GET'){const config=await ensureBotConfig(env),row=await savedSettings(env);return json({config,hasApiKey:!!(row?.key_cipher||env.GEMINI_API_KEY)})}
   if(request.method!=='PUT')return json({error:'Método não permitido.'},405);
   const data=await requestData(request);data.config=completeBotConfig(data.config);if(!validConfig(data.config))return json({error:'Confira a oferta, opções e os cinco modelos de mensagem.'},400);
   const row=await savedSettings(env);if(data.initializeOnly&&row)return json({config:JSON.parse(row.config_json),hasApiKey:!!(row.key_cipher||env.GEMINI_API_KEY)});
   let cipher=row?.key_cipher||null;if(data.removeApiKey===true)cipher=null;else if(data.apiKey){const key=normalizeApiKey(data.apiKey);if(!key||key.length>512)return json({error:'Confira a chave Gemini inserida.'},400);cipher=await encryptSecret(key,env)}
   const operation=data.initializeOnly?'INSERT OR IGNORE INTO settings (id,config_json,key_cipher,updated_at) VALUES (?,?,?,?)':'INSERT INTO settings (id,config_json,key_cipher,updated_at) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET config_json=excluded.config_json,key_cipher=excluded.key_cipher,updated_at=excluded.updated_at';
   await statement(env,operation,1,JSON.stringify(data.config),cipher,new Date().toISOString()).run();const updated=await savedSettings(env);return json({config:JSON.parse(updated.config_json),hasApiKey:!!(updated.key_cipher||env.GEMINI_API_KEY)})
  }
  if(url.pathname==='/api/history'&&request.method==='GET'){const result=await statement(env,'SELECT s.id,s.company,s.phone,s.message,s.type,s.opened_at AS date,s.status,s.confirmed_at AS confirmedAt,COALESCE(q.contact_id,m.contact_id) AS contactId,c.city,c.responsible,c.notes,COALESCE(q.instance_name,i.name) AS instanceName,c.interested,c.ai_paused AS aiPaused FROM sends s LEFT JOIN send_queue q ON q.id=s.id LEFT JOIN ai_messages m ON m.id=s.id LEFT JOIN instances i ON i.id=m.instance_id LEFT JOIN contacts c ON c.id=COALESCE(q.contact_id,m.contact_id) ORDER BY s.opened_at DESC').all();return json({entries:result.results||[]})}
  if(url.pathname==='/api/history'&&request.method==='POST'){const data=await requestData(request,20000);if(!data||typeof data.id!=='string'||!data.id||data.id.length>100||typeof data.company!=='string'||!data.company.trim()||data.company.length>150||typeof data.phone!=='string'||!/^\d{10,15}$/.test(data.phone)||typeof data.message!=='string'||data.message.length>10000||typeof data.type!=='string'||data.type.length>100)return json({error:'Confira os dados do envio.'},400);
   const date=typeof data.date==='string'&&!isNaN(Date.parse(data.date))?new Date(data.date).toISOString():new Date().toISOString();const status=data.imported&&data.status==='sent'?'sent':'opened';
   await statement(env,'INSERT OR IGNORE INTO sends (id,company,phone,message,type,opened_at,status,confirmed_at) VALUES (?,?,?,?,?,?,?,?)',data.id,data.company,data.phone,data.message,data.type,date,status,status==='sent'?date:null).run();return json({success:true})
  }
  if(url.pathname.startsWith('/api/history/')&&request.method==='PATCH'){const id=decodeURIComponent(url.pathname.slice('/api/history/'.length));const result=await statement(env,'UPDATE sends SET status = ?,confirmed_at = ? WHERE id = ?','sent',new Date().toISOString(),id).run();return result.meta?.changes?json({success:true}):json({error:'Registro não encontrado.'},404)}
  return json({error:'Método não permitido.'},405)
 }catch(error){return json({error:error.message==='INPUT_TOO_LARGE'?'Reduza o tamanho das informações.':url.pathname==='/api/queue/prepare'?error.message:'O banco de dados está indisponível. Seus campos foram preservados; tente novamente.'},503)}
}

function resolveSpintax(text){for(let i=0;i<20&&/\{[^{}]*\|[^{}]*\}/.test(text);i++)text=text.replace(/\{([^{}]*\|[^{}]*)\}/g,(_,choices)=>{const parts=choices.split('|');return parts[Math.floor(Math.random()*parts.length)]});return text}
async function generateQueueMessage(env,url,config,company,current){const response=await workerApi.fetch(new Request(url.origin+'/api/generate-message',{method:'POST',headers:{Origin:url.origin,'Content-Type':'application/json'},body:JSON.stringify({company,niche:'Comércio local',goal:'Reescrever o texto atual',tone:config.tone,length:config.length,emojis:config.emojis,details:config.offer,current})}),env);const data=await response.json();if(!response.ok)throw new Error(data.error||'Falha ao preparar mensagem com IA.');return data.message}
async function queueTiming(env){const instances=(await statement(env,"SELECT * FROM instances WHERE status='CONNECTED' ORDER BY updated_at,name").all()).results||[];const processing=await statement(env,"SELECT id FROM send_queue WHERE status='PROCESSING' LIMIT 1").first();const ready=instances.find(i=>!i.rest_until||Date.parse(i.rest_until)<=Date.now());return {processing:!!processing,nextSendAt:ready?new Date().toISOString():instances.map(i=>i.rest_until).sort()[0]||null}}
async function processQueue(env){
 const rules=await statement(env,'SELECT * FROM send_rules WHERE id=1').first();if(rules?.queue_state!=='RUNNING')return {state:rules?.queue_state||'PAUSED'};
 if(await statement(env,"SELECT id FROM send_queue WHERE status='PROCESSING' LIMIT 1").first())return {processing:true};
 const row=await statement(env,"SELECT q.*,c.company,c.phone FROM send_queue q JOIN contacts c ON c.id=q.contact_id WHERE q.status='QUEUED' ORDER BY q.position LIMIT 1").first();
 if(!row){await statement(env,"UPDATE send_rules SET queue_state='STOPPED' WHERE id=1").run();return {state:'STOPPED',message:'Fila concluída.'}}
 const instances=(await statement(env,"SELECT * FROM instances WHERE status='CONNECTED' ORDER BY updated_at,name").all()).results||[];
 const instance=instances.find(i=>!i.rest_until||Date.parse(i.rest_until)<=Date.now());if(!instance)return {state:'RUNNING',...await queueTiming(env)};
 let prepared;try{prepared=JSON.parse(row.message)}catch{}if(!prepared?.text?.trim())return {error:'Prepare as mensagens antes de iniciar.'};
 const claim=await statement(env,"UPDATE send_queue SET status='PROCESSING',processing_at=?,instance_name=? WHERE id=? AND status='QUEUED' AND NOT EXISTS(SELECT 1 FROM send_queue WHERE status='PROCESSING') AND EXISTS(SELECT 1 FROM send_rules WHERE id=1 AND queue_state='RUNNING')",new Date().toISOString(),instance.name,row.id).run();if(!claim.meta?.changes)return {processing:true};
 let accepted=false;
 try{
  const go=instance.provider==='EVOLUTION_GO',key=await decryptSecret(go?instance.instance_token_cipher:instance.token_cipher,env);
  let response=await fetch(instance.api_url.replace(/\/$/,'')+(go?'/send/text':'/message/sendText/'+encodeURIComponent(instance.name)),{method:'POST',headers:{'Content-Type':'application/json',apikey:key},body:JSON.stringify({number:row.phone,text:prepared.text}),signal:AbortSignal.timeout(30000)});
  if(go&&response.status===404)response=await fetch(instance.api_url.replace(/\/$/,'')+'/message/sendText',{method:'POST',headers:{'Content-Type':'application/json',apikey:key},body:JSON.stringify({number:row.phone,text:prepared.text}),signal:AbortSignal.timeout(30000)});
  let result={};try{result=await response.json()}catch{}
  if(!response.ok||result.error||result.success===false)throw new Error('A integração recusou o envio (HTTP '+response.status+').');accepted=true;
  const now=new Date().toISOString();
  // Persist the exact accepted text before removing the contact from the active lists.
  await statement(env,'INSERT OR IGNORE INTO sends(id,company,phone,message,type,opened_at,status,confirmed_at) VALUES(?,?,?,?,?,?,?,?)',row.id,row.company,row.phone,prepared.text,prepared.type,now,'sent',now).run();
  await statement(env,"UPDATE contacts SET status=CASE WHEN interested=1 THEN 'INTERESTED' ELSE 'SENT' END,last_sent_at=?,last_instance=? WHERE id=?",now,instance.name,row.contact_id).run();
  await statement(env,"UPDATE send_queue SET status='SENT',sent_at=?,error=NULL WHERE id=?",now,row.id).run();
  const count=(instance.rest_until&&Date.parse(instance.rest_until)<=Date.now()&&instance.sent_in_cycle>=instance.messages_per_cycle?0:instance.sent_in_cycle)+1;
  const min=Number(instance.min_seconds),max=Math.max(min,Number(instance.max_seconds));const delay=count>=instance.messages_per_cycle?Number(instance.rest_minutes)*60:min+Math.floor(Math.random()*(max-min+1));
  await statement(env,'UPDATE instances SET sent_in_cycle=?,rest_until=?,updated_at=? WHERE id=?',count,new Date(Date.now()+delay*1000).toISOString(),now,instance.id).run();
  await event(env,row.contact_id,'SENT',JSON.stringify({queueId:row.id,instance:instance.name,message:prepared.text}));return {sent:true,...await queueTiming(env)};
 }catch(error){
  const message=accepted?'Envio aceito, mas o registro falhou. Confira o histórico antes de repetir.':error.name==='TimeoutError'?'Tempo de resposta esgotado. Confira o WhatsApp antes de repetir.':error.message;
  await statement(env,"UPDATE send_queue SET status='ERROR',error=? WHERE id=?",message,row.id).run();
  await statement(env,"UPDATE send_rules SET queue_state='PAUSED' WHERE id=1").run();return {state:'PAUSED',error:message};
 }
}
